---
- name: Install packages
  ansible.builtin.package:
    name:
      - git
      - zsh
      - stow
    state: present
  become: "{{ dotfiles_require_root }}"

- name: Clone dotfiles reopository
  ansible.builtin.git:
    repo: "{{ dotfiles_git_url }}"
    version: "{{ dotfiles_git_version }}"
    dest: "{{ dotfiles_git_dest }}"
    update: false
    clone: true
    accept_newhostkey: true

- name: Clone oh-my-zsh reopository
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    version: master
    dest: "{{ dotfiles_omz_dest }}"
    update: false
    clone: true
    depth: 1
    accept_newhostkey: true

- name: Clone powerlevel10k reopository
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    version: master
    dest: "{{ dotfiles_p10k_dest }}"
    update: false
    clone: true
    depth: 1
    accept_newhostkey: true

- name: Unstow
  ansible.builtin.command:
    cmd: "stow --dir {{ dotfiles_git_dest }} --target {{ ansible_env.HOME }} --delete unix-common"
  changed_when: false

- name: Stow
  ansible.builtin.command:
    cmd: "stow --verbose=2 --dir {{ dotfiles_git_dest }} --target {{ ansible_env.HOME }} --stow unix-common"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'

# - name: Unstow everything
#   shell: "stow -D . --target {{ ansible_env.HOME }}"
#   changed_when: false

# - name: Run stow
#   shell: "stow . --target {{ ansible_env.HOME }} --verbose=2"
#   register: result
#   changed_when: 'result.stderr is search("LINK: ")'


