---
- name: Set macOS system preferences
  ansible.builtin.include_tasks: macos-prefs.yml

# - name: Import roles specific to macOS
#   ansible.builtin.include_role:
#     name:
#       - dotfiles
# #      - better_snap_tool
# #      - mac_mouse_fix
#       - gpg
#       - iterm

- name: Include dotfiles role
  ansible.builtin.include_role: 
    name: dotfiles

- name: Include gpg role
  ansible.builtin.include_role: 
    name: gpg

- name: Include gpg role
  ansible.builtin.include_role: 
    name: ssh

- name: Include iterm role
  ansible.builtin.include_role: 
    name: iterm
