---
- name: Set macOS system preferences
  ansible.builtin.include_tasks: macos-prefs.yml

- name: Import roles specific to macOS
  ansible.builtin.include_role:
    name:
      - dotfiles
#      - better_snap_tool
#      - mac_mouse_fix
      - gpg
      - iterm
