---
###############################################################################
# General UI/UX                                                               #
###############################################################################

- name: Expand save panel by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
    state: present

- name: Expand save panel by default2
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode2
    type: bool
    value: true
    state: present

- name: Expand print panel by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: true
    state: present

- name: Expand print panel by default2
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint2
    type: bool
    value: true
    state: present

- name: Save to disk (not to iCloud) by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
    state: present

- name: Disable automatic capitalization
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false
    state: present

- name: Disable automatic period substitution
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: Disable smart quotes
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: Disable auto-correct
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
    state: present

###############################################################################
# Screen                                                                      #
###############################################################################

- name: Enable subpixel font rendering on non-Apple LCDs
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleFontSmoothing
    type: int
    value: 1
    state: present

- name: Save screenshots in PNG format
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png
    state: present

###############################################################################
# Finder                                                                      #
###############################################################################

- name: Show all filename extensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    state: present

- name: Keep folders on top when sorting by name
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
    state: present

- name: When performing a search, search the current folder by default
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf
    state: present

- name: Disable the warning when changing a file extension
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
    state: present

- name: Avoid creating .DS_Store files on network volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
    state: present

- name: Avoid creating .DS_Store files on USB volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true
    state: present

- name: Enable AirDrop over Ethernet and on unsupported Macs running Lion
  community.general.osx_defaults:
    domain: com.apple.NetworkBrowser
    key: BrowseAllInterfaces
    type: bool
    value: true
    state: present

###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################

- name: Minimize windows into their application icon
  community.general.osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
    state: present

- name: Show indicator lights for open applications in the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true
    state: present

###############################################################################
# Time Machine                                                                #
###############################################################################

- name: Prevent Time Machine from prompting to use new hard drives as backup volume
  community.general.osx_defaults:
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true
    state: present

###############################################################################
# Photos                                                                      #
###############################################################################

- name: Prevent Time Machine from prompting to use new hard drives as backup volume
  community.general.osx_defaults:
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true
    state: present

- name: Configure dock
  ansible.builtin.import_role: geerlingguy.mac.dock

  