---
- name: Create ~/bin dir if it doesn't exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/bin"
    state: directory
    mode: "0751"

- name: Set path in profile
  ansible.builtin.lineinfile:
    dest: /etc/profile
    insertafter: EOF
    line: PATH=$HOME/bin:$PATH
  become: true
