---
- name: Create ~/bin dir if it doesn't exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: "0700"

- name: Add user bin dir to zshenv
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshenv"
    insertafter: EOF
    line: PATH=$HOME/bin:$PATH
    create: true

- name: Install and configure oh my zsh
  ansible.builtin.import_role:
    name: diodonfrost.ohmyzsh
  vars:
    ohmyzsh_users:
      - "{{ personal_username_primary }}"
    ohmyzsh_theme: powerlevel10k/powerlevel10k
    ohmyzsh_plugins:
      - git
      - docker

- name: Install custom shell files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/{{ (item | basename) }}"
    owner: "{{ personal_username_primary }}"
    group: staff
    mode: "0600"
  with_fileglob:
    - shell/*.zsh

- name: Install powerlevel10k omz theme
  ansible.builtin.import_role:
    name: diodonfrost.p10k
  vars:
    p10k_users:
      - "{{ personal_username_primary }}"
    zsh_plugin: ohmyzsh
    # Valid values: lean, classic, rainbow, pure
    p10k_prompt_style: classic

    # Show current time
    # Valid values: no, 24-hour, 12-hour
    p10k_prompt_time: 24-hour

    # Prompt sperator
    # Valid values: angled, vertical, slanted, round
    p10k_prompt_separator: angled

    # Prompt heads
    # Valid values: sharp, blurred, slanted, round
    p10k_prompt_head: sharp

    # Prompt tails
    # Valid values: flat, blurred, sharp, slanted, round
    p10k_prompt_tails: flat

    # Terminal prompt height
    # Valid values: one-line, two-lines
    p10k_prompt_height: two-lines

    # Prompt connection, only used if "p10k_prompt_height" value is "two-lines"
    # Valid values: disconnected, dotted, solid
    p10k_prompt_connection: disconnected

    # Prompt connection color, only used if
    # "p10k_prompt_connection" value is "dotted" or "solid"
    # or "p10k_prompt_frame" is not "no"
    # Valid values: lightest, light, dark, darkest, black, white, green, blue
    p10k_prompt_connection_color: dark

    # Prompt frame connection
    # Valid values: no, left, right, full
    p10k_prompt_frame: left

    # Sparse prompt with an empty line before promp
    # Valid values: compact, sparse
    p10k_prompt_spacing: sparse

    # Terminal flow
    # Valid values: concise, fluent
    p10k_prompt_flow: concise

    # Enable transient prompt
    # Valid values: yes, no
    p10k_transient_prompt: "no"
