---
- name: Kill gpg-agent
  ansible.builtin.command: gpgconf --kill gpg-agent
  changed_when: true

- name: Restart gpg-agent
  ansible.builtin.systemd_service:
    name: gpg-agent
    state: restarted
